// vue/players_CRUD/src/App.vue
<!-- 
  COPY AND PASTE YOUR CODE FROM THE PREVIOUS EXERCISE HERE. Also implement the following:

  1. Create a method for adding a new player. This method should handle the logic for adding a new player to the backend and updating the players list. This method should also reset the form only if the request was successful. This method should be called when the add player form is submitted.

  2. Create a method for deleting a player. This method should handle the logic for deleting a player from the backend and updating the players list. This method should be called when the delete button is clicked in the SelectedPlayer component.

  3. Create a method for updating a player. This method should handle the logic for updating a player in the backend and updating the players list. This method should be called when the update button is clicked in the SelectedPlayer component.
 -->


<template>
  <div>
    <RequestStatus/>
    <AddPlayer/>
    <ListPlayers/>
    <SelectedPlayer/>
  </div>
</template>

<script>
import AddPlayer from './components/AddPlayer.vue';
import ListPlayers from './components/ListPlayers.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';
import RequestStatus from './components/RequestStatus.vue';

const REQ_STATUS = {
  loading: 'Loading...',
  success: 'Finished!',
  error: 'An error has occurred!!!'
};

export default {
  components: {
    AddPlayer,
    ListPlayers,
    SelectedPlayer,
    RequestStatus
  },
};
</script>

// react/players_CRUD/src/App.jsx
/**
 * Copy paste your code from the App.jsx file here from the previous exercise.
 *
 * Use similar logic as in the Vue CRUD exercise to create a new player in the
 * backend when the user submits the form in the AddPlayer component.
 *
 * Likewise, add logic to update the player in the backend when the user clicks
 * the update button in the SelectedPlayer component.
 *
 * Finally, add logic to delete the player in the backend when the user clicks
 * the delete button in the SelectedPlayer component.
 *
 * HINT: Before the above logic, it may be better to start by updating the SelectedPlayer component to use the new props.
 *
 * REMEMBER: use the same ids, classes and attributes as in the Vue exercise in
 * the same places to pass the tests. Remember to pass in the appropriate props
 * to the child components.
 *
 * BEWARE: The component props may be different from the Vue exercise and the
 * tests will not pass if you use the wrong props.
 *
 * @format
 */

import { ListPlayers } from './components/ListPlayers.jsx';
import { AddPlayer } from './components/AddPlayer';
import { RequestStatus } from './components/RequestStatus';
import { SelectedPlayer } from './components/SelectedPlayer.jsx';

const REQ_STATUS = {
	loading: 'Loading...',
	success: 'Finished!',
	error: 'An error has occurred!!!',
};

function App() {
	return (
		<>
			<RequestStatus />
			<AddPlayer />
			<ListPlayers />
			<SelectedPlayer />
		</>
	);
}

export default App;
