// redux/react_redux/src/components/RequestStatus.jsx
/** @format
 * @description
 * Student instructions:
 * Copy paste your code from the RequestStatus.jsx file here from the previous week. Implement redux logic to fetch the status from the redux store.
 * BEWARE: No props are passed to this component from now on. Instead, all the data is fetched and updated in the redux store.
 */
export const RequestStatus = ({ status }) => {
  return (
    <div>
      <h3>Request status</h3>
      TODO: RequestStatus
    </div>
  );
};

// vue/players_CRUD/src/components/RequestStatus.vue
<!-- 
  Copy paste your code from the RequestStatus.vue file here from the previous exercise
 -->


 <template>
  <div>
    <h3>Request status</h3>
    TODO: RequestStatus
  </div>
</template>

<script>
export default {
};
</script>

<style scoped>
#request-status {
  content: " ";
  margin: var(--main-margin);
  padding: 20px;
  /* height: 40px; */
  background-color: var(--color-background-soft);
  border: 2px solid var(--color-background-mute);
}
</style>
