// vue/players_CRUD2/src/components/ListPlayers.vue
<!-- 
  Copy paste your code from the ListPlayers.vue file here from the previous exercise
 -->

<template>
  <div>
    <h2>List of players</h2>
    TODO: ListPlayers
  </div>
</template>

<script>
import ListPlayer from './ListPlayer.vue';

export default {

};
</script>

<style scoped>
#players-list {
  list-style: none;
  margin: var(--main-margin);
  padding: 20px;
  background-color: var(--color-background-soft);
}


</style>

// react/players_CRUD/src/components/ListPlayers.jsx
/**
 * Copy paste your code from the ListPlayers.jsx file here from the previous exercise
 */

import { ListPlayer } from './ListPlayer';

export const ListPlayers = ({ players, selectPlayer }) => {
	return (
		<div>
			<h2>List of players</h2>
			<ul id='players-list'>
				{players &&
					players.map((player) => (
						<ListPlayer key={player.id} name={player.name} id={player.id} onClick={selectPlayer} />
					))}
			</ul>
		</div>
	);
};
