// vue/players_fetch/src/App.vue
<!-- 
  1. Inside the root div element, remember to pass in the appropriate props to the child components.

  2. Create two methods for fetching all players and fetching one specific player. The first method should handle the logic for fetching all the players and displaying them in the players list. The second method should handle the logic for fetching a specific player when that player is clicked in the list. It takes the id of the player as an argument. 

  3. When the component is created, fetch players data and handle it appropriately (store and display).

  Hint: Use the provided REQ_STATUS object to update the request status when necessary. "loading" for when the request is in progress, "success" for when the request is successful, and "error" for when the request has failed.
 -->

 <template>
  <div>
    <RequestStatus/>
    <ListPlayers/>
    <SelectedPlayer/>
  </div>
</template>

<script>
import ListPlayers from './components/ListPlayers.vue';
import RequestStatus from './components/RequestStatus.vue';
import SelectedPlayer from './components/SelectedPlayer.vue';
// Import assets

const REQ_STATUS = {
  loading: 'Loading...',
  success: 'Finished!',
  error: 'An error has occurred!!!'
};

export default {
  components: {
    ListPlayers,
    SelectedPlayer,
    RequestStatus
  },
};
</script>

// react/players_fetch/src/App.jsx
/** 
 * Student instructions:
 *
 * Use the provided components to create a React app that fetches players from
 * the provided API and displays them in a list when the App is first rendered.
 * When a player is clicked in the list, fetch that player and display it in the
 * selected player section. Give ListPlayer a function as its selectPlayer prop:
 * it is used to fetch a specific player and should take a player id as its only
 * argument.
 *
 * You can use the Vue exercise players_fetch as a reference and inspiration.
 *
 * REMEMBER: use the same ids, classes and attributes as in the Vue
 * exercise in the same places to pass the tests. Remember to pass in the
 * appropriate props to the child components.
 *
 * BEWARE: The component props may be different from the Vue exercise
 * and the tests will not pass if you use the wrong props.
 *
 * Hint: Use the provided REQ_STATUS object to update the request status when
 * necessary. "loading" for when the request is in progress, "success" for when
 * the request is successful, and "error" for when the request has failed.
 */

import { ListPlayers } from './components/ListPlayers.jsx';
import { SelectedPlayer } from './components/SelectedPlayer.jsx';
import { RequestStatus } from './components/RequestStatus.jsx';

const REQ_STATUS = {
	loading: 'Loading...',
	success: 'Finished!',
	error: 'An error has occurred!!!',
};

function App() {
	return (
		<>
			<RequestStatus />
			<ListPlayers />
			<SelectedPlayer />
		</>
	);
}

export default App;
